const students = [
  {
    id: 1,
    name: 'Alice Johnson',
    courses: ['Math', 'Spanish', 'History'],
    gpa: 3.65,
    email: 'alice.johnson@example.com',
    phone: '555-111-1111',
    address: '123 Elm Street, Springfield, USA',
  },
  {
    id: 2,
    name: 'Bob Smith',
    courses: ['English', 'Art', 'Computer Science'],
    gpa: 3.75,
    email: 'bob.smith@example.com',
    phone: '555-222-2222',
    address: '456 Oak Avenue, Springfield, USA',
  },
  {
    id: 3,
    name: 'Charlie Brown',
    courses: ['Math', 'Physics', 'Chemistry'],
    gpa: 3.82,
    email: 'charlie.brown@example.com',
    phone: '555-333-3333',
    address: '789 Maple Street, Springfield, USA',
  },
  {
    id: 4,
    name: 'Daisy Martinez',
    courses: ['Biology', 'Geography', 'Spanish'],
    gpa: 3.45,
    email: 'daisy.martinez@example.com',
    phone: '555-444-4444',
    address: '321 Pine Avenue, Springfield, USA',
  },
  {
    id: 5,
    name: 'Ethan Wilson',
    courses: ['Math', 'English', 'Computer Science'],
    gpa: 3.9,
    email: 'ethan.wilson@example.com',
    phone: '555-555-5555',
    address: '567 Cedar Street, Springfield, USA',
  },
  {
    id: 6,
    name: 'Fiona Lee',
    courses: ['Physics', 'Chemistry', 'Art'],
    gpa: 3.78,
    email: 'fiona.lee@example.com',
    phone: '555-666-6666',
    address: '890 Walnut Drive, Springfield, USA',
  },
  {
    id: 7,
    name: 'George Thompson',
    courses: ['History', 'Geography', 'English'],
    gpa: 3.55,
    email: 'george.thompson@example.com',
    phone: '555-777-7777',
    address: '654 Birch Street, Springfield, USA',
  },
  {
    id: 8,
    name: 'Hannah Garcia',
    courses: ['Math', 'Biology', 'Chemistry'],
    gpa: 3.7,
    email: 'hannah.garcia@example.com',
    phone: '555-888-8888',
    address: '987 Oak Lane, Springfield, USA',
  },
  {
    id: 9,
    name: 'Ian Patel',
    courses: ['Computer Science', 'Physics', 'Math'],
    gpa: 3.85,
    email: 'ian.patel@example.com',
    phone: '555-999-9999',
    address: '543 Pine Road, Springfield, USA',
  },
  {
    id: 10,
    name: 'Julia Nguyen',
    courses: ['Chemistry', 'Art', 'History'],
    gpa: 3.6,
    email: 'julia.nguyen@example.com',
    phone: '555-101-0101',
    address: '246 Elm Lane, Springfield, USA',
  },
  {
    id: 11,
    name: 'Kevin Miller',
    courses: ['English', 'Math', 'Physics'],
    gpa: 3.92,
    email: 'kevin.miller@example.com',
    phone: '555-202-0202',
    address: '135 Maple Road, Springfield, USA',
  },
  {
    id: 12,
    name: 'Lily Brown',
    courses: ['Biology', 'Geography', 'Spanish'],
    gpa: 3.73,
    email: 'lily.brown@example.com',
    phone: '555-303-0303',
    address: '678 Cedar Lane, Springfield, USA',
  },
  {
    id: 13,
    name: 'Michael Clark',
    courses: ['Computer Science', 'Art', 'Chemistry'],
    gpa: 3.67,
    email: 'michael.clark@example.com',
    phone: '555-404-0404',
    address: '987 Pine Drive, Springfield, USA',
  },
  {
    id: 14,
    name: 'Natalie Taylor',
    courses: ['History', 'English', 'Math'],
    gpa: 3.8,
    email: 'natalie.taylor@example.com',
    phone: '555-505-0505',
    address: '321 Birch Lane, Springfield, USA',
  },
  {
    id: 15,
    name: 'Oliver Martinez',
    courses: ['Spanish', 'History', 'Geography'],
    gpa: 3.55,
    email: 'oliver.martinez@example.com',
    phone: '555-606-0606',
    address: '654 Elm Road, Springfield, USA',
  },
  {
    id: 16,
    name: 'Penelope Wilson',
    courses: ['Math', 'Physics', 'Chemistry'],
    gpa: 3.88,
    email: 'penelope.wilson@example.com',
    phone: '555-707-0707',
    address: '890 Pine Lane, Springfield, USA',
  },
  {
    id: 17,
    name: 'Quinn Garcia',
    courses: ['English', 'Art', 'Biology'],
    gpa: 3.72,
    email: 'quinn.garcia@example.com',
    phone: '555-808-0808',
    address: '567 Cedar Road, Springfield, USA',
  },
  {
    id: 18,
    name: 'Ryan Lee',
    courses: ['Math', 'Computer Science', 'Physics'],
    gpa: 3.95,
    email: 'ryan.lee@example.com',
    phone: '555-909-0909',
    address: '890 Birch Lane, Springfield, USA',
  },
  {
    id: 19,
    name: 'Samantha Nguyen',
    courses: ['Chemistry', 'Art', 'English'],
    gpa: 3.68,
    email: 'samantha.nguyen@example.com',
    phone: '555-123-2345',
    address: '123 Oak Road, Springfield, USA',
  },
  {
    id: 20,
    name: 'Thomas Patel',
    courses: ['History', 'Math', 'Geography'],
    gpa: 3.82,
    email: 'thomas.patel@example.com',
    phone: '555-234-3456',
    address: '456 Elm Lane, Springfield, USA',
  },
  {
    id: 21,
    name: 'Uma Smith',
    courses: ['Art', 'English', 'History'],
    gpa: 3.75,
    email: 'uma.smith@example.com',
    phone: '555-345-4567',
    address: '789 Maple Road, Springfield, USA',
  },
  {
    id: 22,
    name: 'Victor Johnson',
    courses: ['Computer Science', 'Physics', 'Biology'],
    gpa: 3.83,
    email: 'victor.johnson@example.com',
    phone: '555-456-5678',
    address: '987 Cedar Lane, Springfield, USA',
  },
  {
    id: 23,
    name: 'Wendy Brown',
    courses: ['English', 'Chemistry', 'Math'],
    gpa: 3.77,
    email: 'wendy.brown@example.com',
    phone: '555-567-6789',
    address: '654 Oak Road, Springfield, USA',
  },
  {
    id: 24,
    name: 'Xavier Garcia',
    courses: ['History', 'Geography', 'Art'],
    gpa: 3.62,
    email: 'xavier.garcia@example.com',
    phone: '555-678-7890',
    address: '321 Elm Lane, Springfield, USA',
  },
  {
    id: 25,
    name: 'Yasmine Wilson',
    courses: ['Math', 'Art', 'Physics'],
    gpa: 3.9,
    email: 'yasmine.wilson@example.com',
    phone: '555-789-8901',
    address: '567 Pine Road, Springfield, USA',
  },
  {
    id: 26,
    name: 'Zane Nguyen',
    courses: ['Chemistry', 'Art', 'English'],
    gpa: 3.68,
    email: 'zane.nguyen@example.com',
    phone: '555-890-9012',
    address: '123 Birch Lane, Springfield, USA',
  },
  {
    id: 27,
    name: 'Alice Wang',
    courses: ['History', 'Biology', 'Computer Science'],
    gpa: 3.82,
    email: 'alice.wang@example.com',
    phone: '555-901-0123',
    address: '456 Oak Road, Springfield, USA',
  },
  {
    id: 28,
    name: 'Bob Li',
    courses: ['Math', 'Physics', 'Chemistry'],
    gpa: 3.75,
    email: 'bob.li@example.com',
    phone: '555-012-1234',
    address: '789 Cedar Lane, Springfield, USA',
  },
  {
    id: 29,
    name: 'Cathy Chen',
    courses: ['English', 'Art', 'History'],
    gpa: 3.9,
    email: 'cathy.chen@example.com',
    phone: '555-123-2345',
    address: '987 Elm Lane, Springfield, USA',
  },
  {
    id: 30,
    name: 'David Wu',
    courses: ['Math', 'Biology', 'Computer Science'],
    gpa: 3.65,
    email: 'david.wu@example.com',
    phone: '555-234-3456',
    address: '123 Pine Road, Springfield, USA',
  },
];

module.exports = students;
